// Generated by CoffeeScript 1.4.0

/*

LEGAL COPYRIGHT NOTICE

Copyright (c) Noble Samurai Pty Ltd, 2008-2013. All Rights Reserved.

This software is proprietary to and embodies the confidential technology of Noble Samurai Pty Ltd.
Possession, use, dissemination or copying of this software and media is authorised only pursuant
to a valid written license from Noble Samurai Pty Ltd. Questions or requests regarding permission may
be sent by email to legal@noblesamurai.com or by post to PO Box 477, Blackburn Victoria 3130, Australia.
*/


(function() {

  jQuery(function($) {
    var _ref;
    if ((_ref = window.ssam) == null) {
      window.ssam = {};
    }
    return _.extend(window.ssam, {
      bindAll: function(that) {
        var funcs, i, validKeys;
        funcs = Array.prototype.slice.call(arguments, 1);
        validKeys = [];
        if (funcs.length === 0) {
          for (i in that) {
            if (that[i] && typeof that[i] === 'function' && (!that[i].prototype || _.keys(that[i].prototype).length === 0)) {
              validKeys.push(i);
            }
          }
          _.bindAll.apply(_, [that].concat(validKeys));
        } else {
          _.bindAll.apply(_, arguments);
        }
      },
      templateOptions: {
        evaluate: /<#([\s\S]+?)#>/g,
        interpolate: /\{\{\{([\s\S]+?)\}\}\}/g,
        escape: /\{\{([^\}]+?)\}\}(?!\})/g
      },
      template: _.memoize(function(id) {
        var compiled,
          _this = this;
        compiled = null;
        return function(data) {
          if (compiled == null) {
            compiled = _.template($('#tmpl-ss-banner-' + id).html(), null, _this.templateOptions);
          }
          return compiled(data);
        };
      }),
      ajax: function(action, options) {
        if (options == null) {
          options = {};
        }
        options = _.defaults(options, {
          type: 'POST',
          url: ajaxurl,
          context: this
        });
        options.data = _.extend(options.data || {}, {
          action: action
        });
        return $.Deferred(function(deferred) {
          if (options.success) {
            deferred.done(options.success);
          }
          if (options.error) {
            deferred.fail(options.error);
          }
          delete options.success;
          delete options.error;
          return $.ajax(options).done(function(response) {
            if (response === '1' || response === 1) {
              response = {
                success: true
              };
            }
            if ((response != null ? response.success : void 0) != null) {
              return deferred[response.success ? 'resolveWith' : 'rejectWith'](this, [response.data]);
            } else {
              return deferred.rejectWith(this, [response]);
            }
          }).fail(function() {
            return deferred.rejectWith(this, arguments);
          });
        }).promise();
      },
      reduce: function(obj, pre) {
        return _.reduce(obj, function(acc, val, key) {
          if (pre != null) {
            key = "" + pre + "." + key;
          }
          if (_.isObject(val)) {
            return _.extend(acc, window.ssam.reduce(val, key));
          } else {
            acc[key] = val;
            return acc;
          }
        }, {});
      }
    });
  });

}).call(this);
