// Generated by CoffeeScript 1.4.0

/*

LEGAL COPYRIGHT NOTICE

Copyright (c) Noble Samurai Pty Ltd, 2008-2013. All Rights Reserved.

This software is proprietary to and embodies the confidential technology of Noble Samurai Pty Ltd.
Possession, use, dissemination or copying of this software and media is authorised only pursuant
to a valid written license from Noble Samurai Pty Ltd. Questions or requests regarding permission may
be sent by email to legal@noblesamurai.com or by post to PO Box 477, Blackburn Victoria 3130, Australia.
*/


(function() {

  jQuery(function($) {
    var ScarcitySamuraiBanner;
    ScarcitySamuraiBanner = (function() {

      function ScarcitySamuraiBanner($bannerWrapper) {
        var showAfter,
          _this = this;
        this.$bannerWrapper = $bannerWrapper;
        this.inline = $('> .ss-banner-inline', this.$bannerWrapper).length > 0;
        this.$banner = $('.ss-banner', this.$bannerWrapper);
        if (!this.inline) {
          this.$bannerWrapper.appendTo(document.body);
        }
        this.createBindings();
        showAfter = this.$bannerWrapper.data('show-after');
        if (showAfter != null) {
          this.deadline = this.getUnixTimestamp() + showAfter;
          this.value = this.updateTimer();
          this.intervalID = setInterval(function() {
            _this.value = _this.updateTimer();
            if (_this.value > 0) {
              return;
            }
            clearInterval(_this.intervalID);
            return _this.revealBanner();
          }, 1000);
        } else {
          this.revealBanner();
        }
      }

      ScarcitySamuraiBanner.prototype.getUnixTimestamp = function() {
        return Math.round((new Date()).getTime() / 1000);
      };

      ScarcitySamuraiBanner.prototype.updateTimer = function() {
        return Math.max(this.deadline - this.getUnixTimestamp(), 0);
      };

      ScarcitySamuraiBanner.prototype.createBindings = function() {
        return $('.ss_banner_administration_view_link', this.$banner).click(function() {
          return alert("It looks like you're logged in as the admin of this site,\nso when you reload the page the timer will restart - this is expected behaviour.\nTry viewing your campaign in another browser, logging out of admin,\nor in a private browser to see how your campaign performs for new users.");
        });
      };

      ScarcitySamuraiBanner.prototype.revealBanner = function() {
        this.$bannerWrapper.show();
        return this.$banner.slideDown({
          duration: 500,
          easing: 'linear'
        });
      };

      return ScarcitySamuraiBanner;

    })();
    $('.ss-banner-wrapper').each(function() {
      return new ScarcitySamuraiBanner($(this));
    });
  });

}).call(this);
