// Generated by CoffeeScript 1.4.0

/*

LEGAL COPYRIGHT NOTICE

Copyright (c) Noble Samurai Pty Ltd, 2008-2013. All Rights Reserved.

This software is proprietary to and embodies the confidential technology of Noble Samurai Pty Ltd.
Possession, use, dissemination or copying of this software and media is authorised only pursuant
to a valid written license from Noble Samurai Pty Ltd. Questions or requests regarding permission may
be sent by email to legal@noblesamurai.com or by post to PO Box 477, Blackburn Victoria 3130, Australia.
*/


(function() {

  jQuery(function($) {
    var $bannerSelects, $currentBannerSelect, banner, banners, controller, getBanners, getFormatFunction, getFormatSelectionFunction, updateSelects;
    banner = window.ssam.banner;
    banners = new banner.model.Banners;
    controller = new banner.controller.Editor({
      page: $(this).data('page')
    });
    getBanners = function(inline) {
      return banners.filter(function(b) {
        return b.get('data.inline') || false === inline || false;
      });
    };
    getFormatFunction = function(object, container, query) {
      var $el, markup, model, view;
      if (!object.id) {
        return object.text;
      }
      model = banners.get(object.id);
      controller.banner = model;
      view = new banner.view.Banner({
        editable: false,
        bannerClass: "ss-banner-preview-" + object.id,
        model: model,
        controller: controller
      });
      markup = [];
      Select2.util.markMatch(model.get('name'), query.term, markup, function(m) {
        return m;
      });
      $el = $('<div>').html(banner.template('select-preview')({
        title: markup.join('')
      }));
      $('.ss-banner-overlay', $el).append(view.render().el);
      return $el;
    };
    getFormatSelectionFunction = function(object) {
      var model;
      if (!(object != null)) {
        return '';
      }
      if (!object.id) {
        return object.text;
      }
      model = banners.get(object.id);
      return model.get('name');
    };
    $bannerSelects = $('.ss-banner-select');
    $bannerSelects.select2({
      width: 460,
      formatResult: getFormatFunction,
      formatSelection: getFormatSelectionFunction,
      escapeMarkup: function(m) {
        return m;
      },
      sortResults: function(results) {
        return results.sort(function(a, b) {
          a = a.text.toLowerCase();
          b = b.text.toLowerCase();
          if (b < a) {
            return 1;
          } else if (a < b) {
            return -1;
          } else {
            return 0;
          }
        });
      }
    });
    updateSelects = function($selects) {
      return _.defer(function() {
        return $selects.each(function() {
          return $(this).select2('val', $(this).data('value')).change();
        });
      });
    };
    $currentBannerSelect = null;
    banners.on('add', function(banner) {
      var $newBannerOption, $updateBannerSelects;
      $newBannerOption = $('<option>').val(banner.id).text(banner.get('name'));
      $updateBannerSelects = $bannerSelects.filter(function() {
        return ($(this).data('inline') || false) === (banner.get('data.inline') || false);
      });
      $updateBannerSelects.append($newBannerOption);
      return updateSelects($updateBannerSelects);
    });
    banners.on('remove', function(banner) {
      var $updateBannerSelects, firstValue;
      $updateBannerSelects = $bannerSelects.filter(function() {
        return ($(this).data('inline') || false) === (banner.get('data.inline') || false);
      });
      $updateBannerSelects.find("[value='" + banner.id + "']").remove();
      firstValue = $currentBannerSelect.find('option:first-child').attr('value');
      return $currentBannerSelect.select2('val', firstValue);
    });
    $.when(banners.fetch()).done(function() {
      return updateSelects($bannerSelects);
    });
    return $bannerSelects.each(function() {
      var $link,
        _this = this;
      $link = $('<a>').addClass('ss-banner-select-customize').attr('href', '#').text('Customize Banner');
      $link.on('click', function(event) {
        var editor;
        event.preventDefault();
        $currentBannerSelect = $(_this);
        controller.banner = banners.get(_this.value).clone();
        editor = banner.editor({
          page: $(_this).data('page'),
          id: _this.value,
          controller: controller
        });
        editor.banner.on('created', function(data) {
          $currentBannerSelect.data('value', data.id);
          return banners.add(new banner.model.Banner(data));
        });
        editor.banner.on('updated', function(data) {
          return banners.get(data.id).set(data).elements.reset(data.elements);
        });
        return editor.banner.on('deleted', function(data) {
          $currentBannerSelect.data('value', null);
          return banners.remove(banners.get(data.id));
        });
      });
      return $(this).after($link);
    });
  });

}).call(this);
