// Generated by CoffeeScript 1.4.0

/*

LEGAL COPYRIGHT NOTICE

Copyright (c) Noble Samurai Pty Ltd, 2008-2013. All Rights Reserved.

This software is proprietary to and embodies the confidential technology of Noble Samurai Pty Ltd.
Possession, use, dissemination or copying of this software and media is authorised only pursuant
to a valid written license from Noble Samurai Pty Ltd. Questions or requests regarding permission may
be sent by email to legal@noblesamurai.com or by post to PO Box 477, Blackburn Victoria 3130, Australia.
*/


(function() {

  jQuery(function($) {
    var _ref, _ref1;
    $.extend($.datepicker, {
      _checkOffset: function(inst, offset, isFixed) {
        return offset;
      }
    });
    if (((_ref = $.ui) != null ? _ref.dialog : void 0) != null) {
      $.extend($.ui.dialog.prototype.options, {
        dialogClass: 'wp-dialog',
        modal: true,
        resizable: false,
        open: function() {
          return $('.ui-dialog-buttonset button:first-child').blur();
        }
      });
    }
    if (((_ref1 = $.ui) != null ? _ref1.sortable : void 0) != null) {
      $.extend($.ui.sortable.prototype.options, {
        revert: true,
        tolerance: 'pointer'
      });
    }
    $('<div id="confirmation_dialog">Are you sure?</div>').appendTo('body');
    $.showConfirmationDialog = function(options) {
      var defaults, settings;
      defaults = {
        buttons: {
          No: {
            text: 'No',
            "class": 'scarcity_samurai_button',
            click: function() {
              return $(this).dialog('close');
            }
          }
        }
      };
      options.buttons = $.extend({}, defaults.buttons, options.buttons);
      settings = $.extend({}, defaults, options);
      $('#confirmation_dialog').dialog(settings);
    };
    $.hideConfirmationDialog = function() {
      return $('#confirmation_dialog').dialog('close');
    };
    $('<div id="message_dialog"></div>').appendTo('body');
    $.showMessageDialog = function(message, options) {
      var defaults, settings;
      defaults = {};
      options.buttons = $.extend({}, defaults.buttons, options.buttons);
      settings = $.extend({}, defaults, options);
      $('#message_dialog').html(message).dialog(settings).css('min-height', '');
    };
    return $.hideMessageDialog = function() {
      return $('#message_dialog').dialog('close');
    };
  });

}).call(this);
