// Generated by CoffeeScript 1.4.0

/*

LEGAL COPYRIGHT NOTICE

Copyright (c) Noble Samurai Pty Ltd, 2008-2013. All Rights Reserved.

This software is proprietary to and embodies the confidential technology of Noble Samurai Pty Ltd.
Possession, use, dissemination or copying of this software and media is authorised only pursuant
to a valid written license from Noble Samurai Pty Ltd. Questions or requests regarding permission may
be sent by email to legal@noblesamurai.com or by post to PO Box 477, Blackburn Victoria 3130, Australia.
*/


(function() {

  jQuery(function($) {
    var ScarcitySamuraiTimer, serverNow, timerData, timerId, _ref;
    serverNow = parseInt(scarcitySamuraiData.now);
    ScarcitySamuraiTimer = (function() {

      function ScarcitySamuraiTimer($timerWrapper, timerData) {
        var clientNow, _ref,
          _this = this;
        this.$timerWrapper = $timerWrapper;
        this.$days = $('.ss-days', this.$timerWrapper);
        this.$hours = $('.ss-hours', this.$timerWrapper);
        this.$minutes = $('.ss-minutes', this.$timerWrapper);
        this.$seconds = $('.ss-seconds', this.$timerWrapper);
        clientNow = this.getUnixTimestamp();
        this.serverTimeOffset = clientNow - serverNow;
        this.deadline = timerData.deadline;
        if (this.$timerWrapper.is('.ss-styled-timer')) {
          this.format = 'styled';
        } else {
          this.format = (_ref = timerData.format) != null ? _ref : 'text';
        }
        this.redirectURL = timerData.redirect_url;
        this.value = this.updateTimer();
        this.intervalID = setInterval(function() {
          _this.value = _this.updateTimer();
          if (_this.value > 0) {
            return;
          }
          clearInterval(_this.intervalID);
          _this.onExpire();
        }, 1000);
      }

      ScarcitySamuraiTimer.prototype.getUnixTimestamp = function() {
        return Math.round((new Date()).getTime() / 1000);
      };

      ScarcitySamuraiTimer.prototype.pluralize = function(count, word) {
        return count + ' ' + word + (count === 1 ? '' : 's');
      };

      ScarcitySamuraiTimer.prototype.zeroPrefix = function(number) {
        if (number < 10) {
          return "0" + number;
        } else {
          return "" + number;
        }
      };

      ScarcitySamuraiTimer.prototype.updateTimer = function() {
        var days, hours, minutes, seconds, timerText, timerValue, value;
        timerValue = value = Math.max(this.deadline - this.getUnixTimestamp() + this.serverTimeOffset, 0);
        days = Math.floor(value / 86400);
        value -= days * 86400;
        hours = Math.floor(value / 3600);
        value -= hours * 3600;
        minutes = Math.floor(value / 60);
        value -= minutes * 60;
        seconds = value;
        switch (this.format) {
          case 'styled':
            this.$days.text(this.zeroPrefix(days));
            this.$hours.text(this.zeroPrefix(hours));
            this.$minutes.text(this.zeroPrefix(minutes));
            this.$seconds.text(this.zeroPrefix(seconds));
            break;
          case 'text':
            timerText = (function() {
              switch (false) {
                case !(days > 0):
                  return this.pluralize(days, 'day');
                case !(hours > 0):
                  return this.pluralize(hours, 'hour');
                case !(minutes > 0):
                  return this.pluralize(minutes, 'minute');
                default:
                  return this.pluralize(seconds, 'second');
              }
            }).call(this);
            this.$timerWrapper.text(timerText);
            break;
          case 'digital':
            timerText = [this.zeroPrefix(days), this.zeroPrefix(hours), this.zeroPrefix(minutes), this.zeroPrefix(seconds)].join(':');
            this.$timerWrapper.text(timerText);
        }
        return timerValue;
      };

      ScarcitySamuraiTimer.prototype.onExpire = function() {
        if (this.redirectURL == null) {
          return;
        }
        window.onbeforeunload = null;
        window.location = this.redirectURL;
      };

      return ScarcitySamuraiTimer;

    })();
    if (scarcitySamuraiData.timer != null) {
      _ref = scarcitySamuraiData.timer;
      for (timerId in _ref) {
        timerData = _ref[timerId];
        new ScarcitySamuraiTimer($(".ss-timer-" + timerId), timerData);
      }
    }
    if (scarcitySamuraiData.end_time_timer != null) {
      new ScarcitySamuraiTimer($(), scarcitySamuraiData.end_time_timer);
    }
    return $('.ss-inline-timer').each(function() {
      var format, timestamp;
      timestamp = parseInt($(this).data('ss-timer-timestamp'));
      if (isNaN(timestamp)) {
        timestamp = null;
      }
      format = $(this).data('ss-timer-format');
      timerData = {
        deadline: timestamp != null ? timestamp : scarcitySamuraiData.end_time_timer.deadline,
        format: format
      };
      return new ScarcitySamuraiTimer($(this), timerData);
    });
  });

}).call(this);
